# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

baseURL = "/site/"
title = "Agones"
enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
unsafe = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-TK6J08ZNYX"

# Language configuration

[languages]
[languages.en]
title = "Agones"
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.en.params]
description = "Agones is a library for hosting, running and scaling dedicated game servers on Kubernetes."

# Everything below this are Site Params

[params]
copyright = "Copyright Google LLC All Rights Reserved."
privacy_policy = "https://policies.google.com/privacy"
github_repo = "https://github.com/googleforgames/agones"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "016691298986124624340:x7qv2dywdao"

# current release branch. Never is rc.
release_branch = "release-1.41.0"
# the main version. Never is rc.
release_version = "1.41.0"

# shown for production
supported_k8s = ["1.27", "1.28", "1.29"]
k8s_api_version = "1.28"
gke_example_cluster_version = "1.28"
aks_example_cluster_version = "1.28"
eks_example_cluster_version = "1.29"
minikube_example_cluster_version = "1.28.6"
# shown in development (or the next versions that will be supported)
dev_supported_k8s = ["1.27", "1.28", "1.29"]
dev_k8s_api_version = "1.28"
dev_gke_example_cluster_version = "1.28"
dev_aks_example_cluster_version = "1.28"
dev_eks_example_cluster_version = "1.29"
dev_minikube_example_cluster_version = "1.28.6"

# example tag
example_image_tag = "us-docker.pkg.dev/agones-images/examples/simple-game-server:0.33"

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/googleforgames/agones/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/googleforgames/agones/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Slack"
	url = "https://join.slack.com/t/agones/shared_invite/zt-2mg1j7ddw-0QYA9IAvFFRKw51ZBK6mkQ"
	icon = "fab fa-slack"
desc = "Chat with other project users in #users"
[[params.links.user]]
	name = "User mailing list"
	url = "https://groups.google.com/forum/#!forum/agones-discuss"
	icon = "fa fa-envelope"
	desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/agonesdev"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="Community Meetings"
	url = "https://www.youtube.com/playlist?list=PLhkWKwFGACw2dFpdmwxOyUCzlGP2-n7uF"
	icon = "fab fa-youtube"
	desc = "Live discussion of new features and issues, see the <a href=\"https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md#community-meetings\">calendar</a> or <a href=\"https://groups.google.com/forum/#!forum/agones-discuss\">mailing list</a> for details"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/googleforgames/agones"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/agones/shared_invite/zt-2mg1j7ddw-0QYA9IAvFFRKw51ZBK6mkQ"
	icon = "fab fa-slack"
	desc = "Chat with other project developers in #development"
[[params.links.developer]]
	name ="Community Meetings"
	url = "https://www.youtube.com/playlist?list=PLhkWKwFGACw2dFpdmwxOyUCzlGP2-n7uF"
	icon = "fab fa-youtube"
	desc = "Live discussion of new features and issues, see the <a href=\"https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md#community-meetings\">calendar</a> or <a href=\"https://groups.google.com/forum/#!forum/agones-discuss\">mailing list</a> for details"
# [[params.links.developer]]
# 	name = "Developer mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discuss development issues around the project"

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'RELEASE_BRANCH', 'HUGO_ENV', 'RELEASE_VERSION']
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
