# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Track and close stale issues
    
    steps:
    - name: Track and mark stale issues
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 30
        stale-issue-message: >
          This issue is marked as Stale due to inactivity for last 30 days. 
          Please add a comment or remove the label. To avoid being marked as "Stale" please add "awaiting-maintainer" label. Thank you for your contributions '
        stale-issue-label: 'stale'
        exempt-issue-labels: awaiting-maintainer
        ascending: true
        start-date: '2022-10-01T00:00:00Z' # ISO 8601
        debug-only: true
        ACTIONS_STEP_DEBUG: true
        enable-statistics: true
